## Fill in data in the following format :
#Pytorch:
#  version: 2.1
#  dependents:
#    Pillow: [1.1, 2.2, 3.3]
#    Numpy: [1.1, 2.2]
#    Opencv: [1.0]
#  test_method: fuzz
#  docker_container: xxx

Pytorch:
  version: 2.1
  dependents:
    Pillow:  2.2
    Numpy: 1.1
    Opencv: 1.0
  docker_container: 'e79e933124e0'
  shell_command: './run_fuzz.sh'
  test_method: fuzz
  download_addr: xxxx/path

Tensorflow:
  version: 2.1
  dependents:
    Pillow: 2.2
    Numpy: 1.1
    Opencv: 1.0
  docker_container: '62e559a6721b'
  shell_command: 'python fuzz_tensorflow.py'
  test_method: fuzz
  download_addr: xxxx/path

keras:
  version: 2.1
  dependents:
    Pillow: 2.2
    Numpy: 1.1
    Opencv: 1.0
  docker_container: '314ea4f77ed8'
  shell_command: 'python fuzz_keras.py'
  test_method: fuzz
  download_addr: xxxx/path

numpy:
  version: 2.1
  dependents:
    Pillow: 2.2
    Numpy: 1.1
    Opencv: 1.0
  docker_container: '2074dcdc580e'
  shell_command: 'python3 fuzz_numpy.py'
  test_method: fuzz
  download_addr: xxxx/path

opencv:
  version: 2.1
  dependents:
    Pillow: 2.2
    Numpy: 1.1
    Opencv: 1.0
  docker_container: '4a1f3ae9aeb6'
  shell_command: './generateusergallerycollage_fuzzer'
  test_method: fuzz
  download_addr: xxxx/path

pandas:
  version: 2.1
  dependents:
    Pillow: 2.2
    Numpy: 1.1
    Opencv: 1.0
  docker_container: '1c0cf3ac9b49'
  shell_command: 'python3 fuzz_pandas.py'
  test_method: fuzz
  download_addr: xxxx/path

  pillow:
  version: 2.1
  dependents:
    Pillow: 2.2
    Numpy: 1.1
    Opencv: 1.0
  docker_container: '721dbb429554'
  shell_command: './run_fuzz.sh'
  test_method: fuzz
  download_addr: xxxx/path

  scipy:
  version: 2.1
  dependents:
    Pillow: 2.2
    Numpy: 1.1
    Opencv: 1.0
  docker_container: 'e80bbf54414c'
  shell_command: 'python3 fuzz_scipy.py'
  test_method: fuzz
  download_addr: xxxx/path